### ISSUE TITLE
【bug】百度小程序，post form请求服务端收不到请求数据

### ISSUE THREAD

**Issue by lmm1990** [chameleon-team/chameleon-api#6]
![TIM图片20190801144414](https://user-images.githubusercontent.com/4828501/62271329-edc2a400-b46a-11e9-9017-64a246c2e2b7.png)
百度小程序的post form请求，需要用对象的格式，字符串，服务端取不到数据

需要修改的文件：
[https://github.com/chameleon-team/chameleon-api/blob/master/src/interfaces/request/index.js](https://github.com/chameleon-team/chameleon-api/blob/master/src/interfaces/request/index.js)
![TIM图片20190801144841](https://user-images.githubusercontent.com/4828501/62271557-7ccfbc00-b46b-11e9-8796-b9cec7e3d77b.png)

**Comment by AdamEleven** [comment]
如果需要对象格式, 可是尝试在调用的时候传入参数 contentType: 'json' 
看下可以解决你的问题吗?

**Comment by lmm1990** [comment]
需要的是formData post请求

不能解决，原因：网页版、微信小程序版已经写好了，开发百度小程序时遇到了这个问题
改contentType影响很大
百度的  application/x-www-form-urlencoded 也需要传object对象，服务端才能收到数据

百度小程序代码片段：swanide://fragment/a55a5dd5ad7f5d538dd9ea7b1ce2670c1564733696694

你们测试下就知道了

**Comment by AdamEleven** [comment]
chameleon-api@0.5.5-alpha.1
升级一下这个版本试下吧. 做了一些修改

**Comment by lmm1990** [comment]
现在可以用了
